### ISSUE TITLE
Update schemes for tb_speciation and typhi, including metadata

### ISSUE THREAD

**Issue by glabbe** [phac-nml/biohansel#102]
Schemes updated after QC module fix:  update tb_speciation scheme to v1.0.5 with associated metadata, and Typhi scheme to v1.2.0, with attached metadata

[tb_speciation_scheme_v1.0.5.txt](https://github.com/phac-nml/biohansel/files/3393466/tb_speciation_scheme_v1.0.5.txt)
[tb_speciation_v105_metadata.txt](https://github.com/phac-nml/biohansel/files/3393526/tb_speciation_v105_metadata.txt)
[Typhi_scheme_v1.2.0.txt](https://github.com/phac-nml/biohansel/files/3393467/Typhi_scheme_v1.2.0.txt)
[Typhi_schemev1.2.0_metadata_Wong_et_al_genotypes.txt](https://github.com/phac-nml/biohansel/files/3393507/Typhi_schemev1.2.0_metadata_Wong_et_al_genotypes.txt)

**Comment by DarianHole** [comment]
Hi @glabbe,

I'll get to work updating these and testing their inclusion now

**Comment by glabbe** [comment]
Thanks @DarianHole , and please check for extra semicolons as mentioned by Peter in issue #99

**Comment by DarianHole** [comment]
Fixed in #103
