### ISSUE TITLE
Change tb_speciation to tb_lineage?

### ISSUE THREAD

**Issue by dankein** [phac-nml/biohansel#107]
Hi, would it be possible to change the tb_speciation name to tb_lineage without breaking anything? This would be more scientifically correct/ clear to external users.

Thanks!
Dan

**Comment by glabbe** [comment]
OK @dankein, will change for the next update, thanks.

**Comment by DarianHole** [comment]
Done, will be updated in the next release and then the conda recipe can be quickly updated.

Then, we just need to update the galaxy wrapper to accommodate this change too when the conda recipe is released. This is only a few lines to change though and should be easy enough

**Comment by dankein** [comment]
Thank you very much @DarianHole @glabbe

**Comment by Takadonet** [comment]
Fixed
