### ISSUE TITLE
Add sample input grouping based on the regex `_(R1|R2)` to support Illumina instrument output

### ISSUE THREAD

**Issue by peterk87** [phac-nml/biohansel#38]
> FASTQ files are named with the sample name and the sample number, which is a numeric assignment based on the order that the sample is listed in the sample sheet. 
> Example:
> `Data\Intensities\BaseCalls\SampleName_S1_L001_R1_001.fastq.gz`
- http://support.illumina.com/content/dam/illumina-support/help/BaseSpaceHelp_v2/Content/Vault/Informatics/Sequencing_Analysis/BS/swSEQ_mBS_FASTQFiles.htm

> Sample_Name and Sample_ID cannot contain underscore characters (`_`). Underscores cause issues during secondary analysis.
-  https://support.illumina.com/help/BaseSpace_App_UMI_Error_Correction_OLH_1000000035906/Content/Source/Informatics/TruSight_UMI/PrepareSampleSheet_fTST_mUMI.htm

> You can use alphanumeric characters, hyphens [`-`], and underscores [`_`] for the Sample_Project, Sample_ID, and Sample_Name. Sample_ID, Sample_Name, and Sample_Project field entries in the sample sheet cannot contain illegal characters that are not allowed by some file systems. Examples of common characters that are not allowed are the space character and the following: `?()[]/\=+<>:;"',*^| &`.
- https://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl2fastq/bcl2fastq2_guide_15051736_v2.pdf#%5B%7B%22num%22%3A9%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C54%2C470.25%2C0%5D

Potential Illumina FASTQ regular expression?
```regex
^([\w\-\_]+)_S\d+_L\d{3}_R(\d)_001\.fastq(\.gz)?$
```

**Comment by Takadonet** [comment]
Closing issue since incorporated into Galaxy wrapper in May 2018.
