### ISSUE TITLE
Not failing QC with inconsistent results in first hierarchical level

### ISSUE THREAD

**Issue by DarianHole** [phac-nml/biohansel#88]
Samples are passing QC when they have inconsistent results. This is due to the QC module not checking against the first hierarchical level when determining if subtypes are consistent.

ex. A sample should fail QC if it is hitting subtype call 8.1 **but** missing subtype call 8

**Comment by DarianHole** [comment]
@glabbe Can you confirm that I have phrased this issue correctly?

**Comment by glabbe** [comment]
@DarianHole Yes that accurately describes the problem, thanks!

**Comment by Takadonet** [comment]
Resolved
