### ISSUE TITLE
Update New Release to Pypi

### ISSUE THREAD

**Issue by DarianHole** [phac-nml/biohansel#95]
Hi @peterk87, 

When you get a chance, we need you to pull the new biohansel release (v2.2.0) to Pypi so that I can start updating bioconda and galaxy.

**Comment by peterk87** [comment]
Manually uploaded the latest version to PyPI (https://pypi.org/project/bio-hansel/2.2.0/)

```bash
git checkout master && git pull
python setup.py sdist
twine upload dist/bio_hansel-2.2.0.tar.gz
```

It will be nice to have this automatically handled by Travis-CI with #97
